name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies for DualNumbers
      run: dotnet restore DualNumbers/DualNumbers.csproj
    
    - name: Build DualNumbers
      run: dotnet build DualNumbers/DualNumbers.csproj --no-restore
    
    - name: Restore dependencies for DualNumbers.Test
      run: dotnet restore DualNumbers.Test/DualNumbers.Test.csproj
    
    - name: Test DualNumbers.Test
      run: dotnet test DualNumbers.Test/DualNumbers.Test.csproj --no-build --verbosity normal

    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./DualNumbers.Test/TestResults/Coverage/coverage.opencover.xml
        flag-name: run-${{ github.run_id }}
        coveralls-endpoint: https://coveralls.io
